# Generated by Django 5.0.6 on 2024-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
