# Generated by Django 5.0.6 on 2024-05-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accountemailtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='accountemailtoken',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='accountemailtoken',
            table='account_email_token',
        ),
    ]
