# Generated by Django 5.0.6 on 2024-05-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_account_id_accountemailtoken_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountemailtoken',
            name='status',
        ),
    ]
