# Generated by Django 5.0.6 on 2024-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_accountemailtoken_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountemailtoken',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
